### ISSUE TITLE
Add Luven to Light

### ISSUE THREAD

**Issue by chicogamedev** [love2d-community/awesome-love2d#176]
Hi my minimalist light engine with camera integrated is stable and could be useful for others.

https://github.com/chicogamedev/Luven

Thanks

Love the list you're holding !

Cheers, 

Chico

**Comment by JanWerder** [comment]
Thanks for your effort with Luven.
Would you open a PR for adding it to the list?
A short feedback: I had a hard time finding your API docs. I now know that it's in the wiki under API doc, but since it's one of the first things I would look for in a library, maybe a more visible placement in the ReadMe would be nice. Just my two cents.
